### ISSUE TITLE
No works with davinco resolve 18

### ISSUE THREAD

**Issue by dradenvandewind** [deric/DaVinciResolve-metadata#7]
How fit it ?

**Comment by Speagles2** [comment]
I'm using with Resolve 18.5 and it works for me. If you're on a Mac you may be having the path issue in issue #4

**Comment by celdaran** [comment]
I just got it working with 18.6. For me, my `brew install exiftools` failed and I had to grab the pkg file directly from:

https://exiftool.org/install.html#MacOS

I downloaded the raw Lua script file and copied, per the `README`. After that, the thing worked like a charm. This tool is a lifesaver! I'm still surprised something like this isn't built into Resolve itself (seems like sorting by EXIF data -- media created date alone) would be a very popular feature.
