### ISSUE TITLE
Doesn't populate metadata for subclips

### ISSUE THREAD

**Issue by Speagles2** [deric/DaVinciResolve-metadata#9]
Hi Deric
First, thanks for this - awesome, work, just what I was looking for! 

I found a minor issue if your workflow involves subclips: because the API returns the name of the parent file for these, and the name is used as a key in the code, only one subclip gets processed for each clip and gets the exif data populated. 

I made patch to fix this, along with a proposed (hacky) fix for issue #4 and a naming issue with the 'Shutter Speed' field (on resolve 18), and created a pull request for your consideration.

Thanks again!

**Comment by deric** [comment]
Resolved via #8.
